name: perlcritic

on:
  pull_request:
  workflow_dispatch:

jobs:
  perlcritic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Perl::Critic
        run: sudo apt-get update && sudo apt-get install -y libperl-critic-perl
      - name: Run perlcritic
        run: perlcritic --profile .perlcriticrc --quiet src/ plugins/
